Start of dev for PNW PLSE 2024
PNWPLSE/pnwplse.github.io pull request #3
Opened 2024-01-26 18:16 UTC by jyoo980

2024-01-26 18:41 UTC, jyoo980 commented
Here are some screenshots 
![image](https://github.com/PNWPLSE/pnwplse.github.io/assets/24359440/23a9e913-4dea-47b7-9ddb-131ab9020fdf)
![image](https://github.com/PNWPLSE/pnwplse.github.io/assets/24359440/2e0daaf7-35f6-46fa-811a-0ff25407e6cb)

2024-01-27 04:57 UTC, ztatlock requested changes
@jyoo980 left some comments. I think only big thing is keeping the old logo files. Many thanks for pushing this through!!

2024-01-27 04:57 UTC, ztatlock commented on img/pnwplse-logo-designs.key
Let's leave this in the repo. I believe it is the definitive copy of the logo design.

2024-01-27 04:57 UTC, ztatlock commented on img/pnwplse.png
Similarly, I think we probably want to leave this in the repo so we have the logo handy.

2024-01-27 04:57 UTC, ztatlock commented on style.css
What's the provenance on this CSS? PLSE page?

2024-01-27 04:57 UTC, ztatlock commented on index.html
No <html> / <head> / <body> ?! Am I living in the future??

2024-01-27 22:02 UTC, jyoo980 commented on style.css
Yep, it's ripped from the PLSE page but with minor style modifications

2024-01-29 16:22 UTC, ztatlock approved these changes
Looks great! Many thanks again for pushing on this!!

2024-01-29 18:12 UTC, jyoo980 commented
Will merge once Kevin gives the OK on the Google Form

2024-02-01 20:35 UTC, merged